name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  ACTIONS_CACHE_SERVICE_V2: "on"
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_GHA_VERSION: "1"

jobs:
  benchmarks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup environment
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build benchmarks
        run: cargo codspeed build --workspace

      - name: Upload benchmark results to CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: "${{ secrets.STAGING_CODSPEED_TOKEN }}"
          upload-url: https://api.staging.preview.codspeed.io/upload
